/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUZZVmtPT0VkK2Frb3o0c3JUdDNORzVrMUh0REJiTEZkeC9TczUrWWkyRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTFhXTnhEMEtaWDBtZ2JXVS9QamRhT1ZJd3J5V1p1TW8wWjJpbTJnNzN3cz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvQWpFaFBDeC82SmRzd3lqNmlXN3hxMXRseU9qdzNqU2xyUm5KMlpHV0UwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3UE5pejBULzFFSXY1UXZBTWpybVF5aEp2SWR0QmZ0bjJDRVB4cWVSTFZRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNEWGZCQU4rZ0lRTFI2NHk2QUVzdGMwVHEyWUhpd2Z6bmU3QklJdUtLVnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZERFJvZ2I4RURWci9pdnBNRE9xaDFxYWFSc1ZEY3E1QWxBbkJyL2oxVVk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUU9tTHNJUk9sQ21naXp0SmNuZGM1Yjl1d3ZpZVFRN2ZicWkrNkxZSGZYbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidHZocUpSclRTSXlLc0dUY2pZUHFvMGlDOEExL1IrK2hMOFpoS3NVdHFtcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilg2djB2VGI0MWZwRmVBS1hzNlZlNHZuSGp5Y2hTdUFlbVNpQ2pNZG45NkNSTWdad3hETktwS2dNSXNPb09pM3Nlb0xTbkM2WGhKMVUvNTd2N2JBOUNBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODMsImFkdlNlY3JldEtleSI6Ijd5WCtlcjNmc0RWNjNscXQwTzBINE9QUjNNMHF2Y09DTUQ0NEJQVVlzRTQ9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjYzNzE5MTk0MjE0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkVBQzQ1MDQ5MzEzQzM2RjgyN0NDNzA0QTg3RkE4NkNEIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjgzODE0MTd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI2MzcxOTE5NDIxNEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5NkUwQkYyMTYxN0JFQUQxREIzNUE2NkU4OEVEREU2OCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI4MzgxNDI0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJHZ1ZwWEstc1Q1ZU5KdnNDeXV5b25BIiwicGhvbmVJZCI6Ijk3M2U4ODE0LWVhYTgtNDcxNC1iMjBhLWQ4NTFmMzFkMWNjMSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIzT05UcmlFMVNVTi9pbXVWbGx1TXpyMXJZblE9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNGg5N1pDSWlpb1BhUDk1OTFkRVdqekpJYUpBPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlYzUlBSWUo1IiwibWUiOnsiaWQiOiIyNjM3MTkxOTQyMTQ6NjhAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSGFja2VyIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNeVhnUFlGRUwrRGxMZ0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJDWVlyYmQ1dmxQcG9JaW1xMm9CWDAvQVNXRW40TGJYTmw3aGM3N2RORVZNPSIsImFjY291bnRTaWduYXR1cmUiOiJGRFYxQ3BMdjIxNzZCZ2J0SjRUZWROOGRLMHFGZGM2WlRSb0hOVjVkVWFJVzlaTHpCMlNuR3hlMXA5djNZd3VYbEphNmVnQjBHUWpVT2dTQW00WFVBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiU3FXbE85RWpnNkViWkw1SGhiUHZBYzJnbkRNU3lTWGcwcjVHcnVDOS8yWWRiUzJjZmRTRU02aFJIM1FscTJ0K2VWbDNDSm9pdWQzSkljRkxlbG1yQWc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNjM3MTkxOTQyMTQ6NjhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUW1HSzIzZWI1VDZhQ0lwcXRxQVY5UHdFbGhKK0MyMXpaZTRYTyszVFJGVCJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyODM4MTM4OCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFKOGEifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || '𝘚𝘛𝘙𝘐𝘒𝘌𝘙𝘉𝘖𝘠';
const packname = process.env.PACKNAME || 'sᴛʀɪᴋᴇʀʙᴏʏ 🤖';
const dev = process.env.DEV || '263784562833';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'sᴛʀɪᴋᴇʀʙᴏʏᵇᵒᵗ';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
